### ISSUE TITLE
allow use of generators with fit_generator()

### ISSUE THREAD

**Issue by mikkokotila** [autonomio/talos#11]
It seems that the only thing that needs to change is the way validation split is now handled internally. Two options:

- add a parameter "use_generator=True" 
- detect the type of the validation_data parameter

**Comment by valekar** [comment]
Any update on this functionality? Also please do let me know if you need any help on this functionality. I will be glad to help you out.

**Comment by mikkokotila** [comment]
@valekar If you want to take a stab at it and make a PR, I'd be more than happy :)

**Comment by valekar** [comment]
@mikkokotila Sure! I will give it a shot.

**Comment by valekar** [comment]
@sim-san I did not get much time to look at it. So it might take some time to implement this feature. I am still working on it

**Comment by mikkokotila** [comment]
@valekar let me know if you need any pointing out / advice regarding this.

**Comment by valekar** [comment]
@mikkokotila Sure! I would let you know if I face any difficulties

**Comment by xkrieg** [comment]
Hello, I am (relatively) new to deep learning and am very interested in using Talos for hyperparameter optimization on my keras models. I use fit_generator exclusively due training with very large datasets that will not load into RAM. I am very happy that this issue is getting some attention and that development is in the works. @valekar, I am wishing you the best as you work on this feature and am enthusiastically awaiting updates to this issue.

**Comment by valekar** [comment]
@mikkokotila,

I had few questions.  

1. In the code, I noticed that there is this “model” folder, with layers.py code, we can create as many 
    number of hidden layers as you want. So do you want me to still keep this functionality?

2. How do you want me to proceed on writing the code for your project? Can I create files or do you 
    want me to add in the existing files?( I see that if I try to modify the existing code, a lot of changes 
    have to be made in the existing code base in order to incorporate this functionality)

**Comment by valekar** [comment]
@xkrieg Thanks! 

Yes this is a really important functionality that needs to implemented. I will try to finish this as soon as possible. Hopefully :)

**Comment by mikkokotila** [comment]
@xkrieg thanks so much :) Regarding your questions above:

1. yes we need to keep that functionality ideally, but if it becomes really painful for some reason, we could have fit_generator initially work without it (i.e. the user needs to explicitly declare hidden layers and have no option to use those as an optimization parameter)

2. You could read the [contribution guidelines](https://github.com/autonomio/talos/blob/dev/CONTRIBUTING.md) and particularly the section pertaining to [pull requests](https://github.com/autonomio/talos/blob/dev/CONTRIBUTING.md#pull_requests)

**Comment by valekar** [comment]
@mikkokotila  Thanks!

**Comment by mikkokotila** [comment]
@valekar any updates on the generator? This seems to be a popular request :)

**Comment by valekar** [comment]
@mikkokotila I suppose it is going to take more time for me to complete this functionality as I am stuck up with other work. I would be glad if someone else gives a shot at this functionality.

**Comment by Umar-Ayub** [comment]
@mikkokotila  are their any updates on this? Could really use this feature for a couple of models I am working on. Also very practical feature for real world use cases

**Comment by zwep** [comment]
Same here! I am curious about the improvements, or where I might be able to contribute

**Comment by mikkokotila** [comment]
This is open for contribution, and at least for now will be dependent on that alone.

**Comment by mikkokotila** [comment]
Have anyone benchmarked the performance of using fit_generator() as opposed to fit(). It seems that there are important doubts in this regard. Also regarding the use cases, do I gather it correct that there are two different use cases: 

1) data is loaded once and then fit_generator is used
2) data is loaded as-needed while being fed into fit_generator

It seems that the latter potentially solves an important memory problem for very large files regardless of anything else (basically making something otherwise not feasible into feasible).

**Comment by mikkokotila** [comment]
It does look like that whatever is gained in the actual run, is taken up by the process in the end where the results of individual steps are stitched back together. Does somebody have contradicting evidence?

**Comment by tsu3010** [comment]
In terms of use case, I personally use it since most data sources I work with cannot be loaded into memory. That's mainly what fit_generator solves for me.

**Comment by mikkokotila** [comment]
@tsu3010 thanks. Stay tuned, this should progress one way or another now.

**Comment by mikkokotila** [comment]
Can somebody try the current @daily-dev. 

The way it works is by making sure that you have the generator function in the same kernel loaded before you load the input model. Then just make sure that the generator accepts x_train and y_train and that's it. So basically you don't have to change anything except use `fit_generator` instead of `fit`. For example, in my case it looks like this: 

`out = model.fit_generator(generator(x_train, y_train), params['batch_size'])...`

**Comment by AyubQuadri** [comment]
Hello @mikkokotila,

I have taken the latest Daily-dev branch and took MNIST_Fashion dataset, I was able to run the fit_generator function which can be found this repo.
https://github.com/AyubQuadri/HPO-Hyper_Parameter_Optimization-/blob/master/HPO_Fashion_MNIST_generator.py

I have a still the problem of loading the entire images into a numpy array of X as well as Y.

as you can see my current code loads the images of size 60000x28x28x3 into X and corresponding categorical values to Y.
so that this numpy array will be called with ta.scan function. 

so for me loading all this images which are of 70000x244x244x3 is cumbersome. 

please suggest some alternatives.

**Comment by git-commit** [comment]
So how is this supposed  to work? The key feature for me when using `fit_generator` is that you don't have to explicitly load all data into `x`, since it might be to large for memory.
What do I pass talos for `x` and `y` in the `Scan` call?

**Comment by mikkokotila** [comment]
@git-commit can you provide an example use-case for how you would do what you want to do with using a simple keras model and `model.fit_generator()`.

**Comment by git-commit** [comment]
My data generators look like this:
```
data_generator = ImageDataGenerator(preprocessing_function=preprocess_input,
                                    vertical_flip=True,
                                    rotation_range=10,
                                    width_shift_range=0.1,
                                    height_shift_range=0.1)

    train_gen = data_generator.flow_from_directory(
            './data/Train',
            target_size=(img_size, img_size),
            batch_size=batch_size,
            class_mode='categorical')

    test_gen = data_generator.flow_from_directory(
            './data/Valid',
            target_size=(img_size, img_size),
            batch_size=batch_size,
            class_mode='categorical')
```

And later I just call `fit_generator` like this:
(where model is an instance of resnet50 for transfer learning)
```
out = model.fit_generator(train_gen,
                              steps_per_epoch=steps,
                              epochs=epochs,
                              validation_data=test_gen,
                              validation_steps=validation_steps,
```

**Comment by JDonini** [comment]
@git-commit Did you create some example of how to use SCAN with fit_generator?

**Comment by JohanMollevik** [comment]
Did the overloading of Scan ever make it into the code base?
I can confirm that running with fit_generator works as long as you pass dummy data, being able to not pass dummy data would be nice.

**Comment by mikkokotila** [comment]
To be frank, this would be better handled by someone who has intimate understanding related with how generators should work (particularly related with the performance aspect). I've given it the minimal attention that allowed adding a somewhat tested minimal support for using model.fit_generator(). 

@JohanMollevik what do you mean by "passing dummy data" (as opposed to not dummy data).

**Comment by JohanMollevik** [comment]
Regarding dummy data, right now my call to Scan looks like below, I would like to be able to specify None to ` dummyX,dummyY,testX,testY` or at least an empty list (the current code returns the first batch so first 30 or so samples depending on batch size).

        dummyX,dummyY=training_set.__getitem__(0)
        testX,testY=test_set.__getitem__(0)
        tt = talos.Scan( x=dummyX
                        ,y=dummyY
                        ,params=params
                        ,model=model
                        ,x_val=testX
                        ,y_val=testY
                        ,dataset_name=modelname # this is not realy the dataset name, used as experiment_name is unavailible
                        ,experiment_no='0'
                        ,print_params=True
                        #,disable_progress_bar=True
                        ,search_method='random'
                        ,reduction_method='correlation'
                        ,reduction_interval=15
                        ,reduction_window=30
                        ,round_limit=120
                        #,round_limit=40
                        ,clear_tf_session=True
                        )

I am by no means an expert but I think that simply allowing us to ommitt the parameters where I use dummy values and pass None to the model (or allow a model that only takes the params as a parameter) would make the code cleaner. My code works by storing the generators in global scope, I'm using generators in the sense of extending the keras.utils.Sequence class, I have not tried the simple generators based on function with yield.

**Comment by lukashondrich** [comment]
Hi, this projects sounds super nice and helpful! Thanks alot for your effort!
I am kind of stuck right now with the specification of training data ( x and y in the "ta.Scan( )" - call). 
What kind of  dummy-data did you use to make it run?

**Comment by JohanMollevik** [comment]
If you look at the code in my comment you can see that I use the first batch of training and test data as dummy data, these are then not used by the model function which accesses the generators directly from a common scope

**Comment by lukashondrich** [comment]
Thanks, it works better in the sense that I now got a new error message! ;)

it says: 
> `ERROR MESSAGE : 'numpy.ndarray' object is not an iterator`

I guess I forward the wrong variables to the model-function. Which arguments do you pass to your model? 

I also had to comment out the dataset_name parameter in the .Scan - call to circumvent some errors. What did you mean with your comment in your code there?

Note: Im using a normal python generator and not a keras.utils.Sequence class like you. But I doubt that that's the problem right now. 

Any help is greatly appreciated!

**Comment by JohanMollevik** [comment]
My comment is not really relevant for anything but my specific application. What version of the code are you using? Can you post your code or enough of it to see what you are doing?

**Comment by PiaCuk** [comment]
I stumbled upon this issue when trying to optimize hyperparameters for LSTMs, where data has to be shuffled sequence sensitive (time sets where the order of instances matters). I would like to experiment with different batch sizes, but if the generator has to be defined in the global scope, I cannot pass `batch_size` in the params dict. Has anyone found a solution to that?

**Comment by JohanMollevik** [comment]
I wrote a blog post on how to use generators using keras here http://inquisitive.blog/post/2019-03-27-10-43-Utilizing-generators-to-use-Keras-training-with-existing-file-structure
What you can do and I have been doing is to define the generator like in the blog post globally and then inside the model function read the batch size param and run set(batch_size=params['batch_size']) before I call keras fit generator function. I will show how I do this in a futur blog post (about half written as of now).

**Comment by awilliamson** [comment]
@PiaCuk Exactly this. I'm having issues using a fit_generator too for LSTM-based optimisation. Is there any update on this issue? There seems to be a slew of related bugs/symptoms around this topic. (I.e MNIST using fit doesn't have any issues).

**Comment by PiaCuk** [comment]
@awilliamson I instantiate my generator in the function defining the model:
```python
def CNN_LSTM(x, y, x_val, y_val, params):
    model = [...]
    train_generator = create_generator(path,
                                       batch_size=params['batch_size'],
                                       set_size=params['set_size'],
                                       return_sequences=params['return_sequences'])
    val_generator = create_generator(path,
                                     batch_size=params['batch_size'],
                                     set_size=params['set_size'],
                                     return_sequences=params['return_sequences'])
    out = model.fit_generator(generator=train_generator, validation_data=val_generator,
                              epochs=params['epochs'], callbacks=[ta.live()])
    return out, model

dummy_x = np.empty((1, 10, _CHANNELS, _IMG_WIDTH, _IMG_HEIGHT))
dummy_y = np.empty((1, 10))
scan = ta.Scan(x=dummy_x,
               y=dummy_y,
               model=CNN_LSTM,
               params=params,
               grid_downsample=1.0,
               dataset_name='talos_lstm',
               experiment_no='x')

ta.Deploy(scan, 'talos_lstm_x', metric='val_loss', asc=True)
```
This works fine, except for the Deploy() where I get the following error:
> Traceback (most recent call last):
  File "lstm_talos.py", line 110, in <module>
    ta.Deploy(scan, 'talos_lstm_x', metric='val_loss', asc=True)
  File "/home/anaconda3/envs/venv_cuda/lib/python3.6/site-packages/talos/commands/deploy.py", line 34, in __init__
    self.save_data()
  File "/home/anaconda3/envs/venv_cuda/lib/python3.6/site-packages/talos/commands/deploy.py", line 60, in save_data
    x = pd.DataFrame(self.scan_object.x[:100])
  File "/home/anaconda3/envs/venv_cuda/lib/python3.6/site-packages/pandas/core/frame.py", line 424, in __init__
    copy=copy)
  File "/home/anaconda3/envs/venv_cuda/lib/python3.6/site-packages/pandas/core/internals/construction.py", line 146, in init_ndarray
    values = prep_ndarray(values, copy=copy)
  File "/home/anaconda3/envs/venv_cuda/lib/python3.6/site-packages/pandas/core/internals/construction.py", line 249, in prep_ndarray
    raise ValueError('Must pass 2-d input')
ValueError: Must pass 2-d input

I reported this in #282 as well, but got no reply so far.

**Comment by ruojol** [comment]
An example on generators would be nice. I got the scan function working with @PiaCuk example but it takes a lot of time for the experiment to start. I have a huge dataset so a generator is a must.

**Comment by ruojol** [comment]
Also why can't one give the generator object as inputs to scan?

**Comment by mikkokotila** [comment]
>Also why can't one give the generator object as inputs to scan?

That's a good question. Feel free to create a feature request in this regard. It's definitely worth considering. 

Thanks a lot for @PiaCuk for the working example. Would you be willing to create an self-contained example notebook, maybe with some Kaggle dataset?

**Comment by AlexZot** [comment]
@PiaCuk Nice and clear example. I want stay tuned due I'm always using generators.

**Comment by AlexZot** [comment]
@PiaCuk Nice and clear example. I want stay tuned due I'm always using generators.

**Comment by JohanMollevik** [comment]
If anyone wants an example of how to use talos with generators I have an example up on my blog at http://inquisitive.blog/post/2019-08-08-11-59-Hyperparameter-optimization-with-Keras-generators-and-Talos it is not using the latest version of talos but should adapt rather easily.

**Comment by surtr82** [comment]
Hi Mikko, are there any news concerning the overloaded scan and evaluate functions? At the moment I'm using Johan's workaround mentioned above.
