### ISSUE TITLE
How to pass a dict of data?

### ISSUE THREAD

**Issue by frederikfaye** [autonomio/talos#145]
I have collected all my data in a `dict` called `data`. This is convenient for me since my model takes multiple inputs, let's call them `x_0, x_1`. I can access these numpy arrays as for instance `data['val']['x_0']` for my validation data of `x_0`, or `data['test']['y']` for my test data of targets. 

Furthermore (this shouldn't matter, but let me mention it, so that it is hopefully less confusing), inside the model creation function passed to Talos, I have defined another `dict` called `hp`, which collects all hyperparameters used by my Keras model. This is *not* used as the `params` of the Talos API. 

To explain what I want to do, let me show a simplified example of what my standard (non-Talos) Keras script does:

```# Imports
import argparse
import numpy as np
import keras as ks
import talos as ta
# and so on ...

from my_functions import load_data, create_model, train

# Load data
data = load_data('./my_data.h5')

# Set hyperparameters
hp = {'epochs'                     : 1000,
      'batch_size'                 : 256,
      'loss'                       : 'logcosh'}

# Build model
model = create_model(input_shapes=[data['train']['x_0'].shape[1:], data['train']['x_1'].shape[1:]], params=hp)

# Train
history, model = train(model=model, data=data, params=hp)

# Evaluate (predicting on test set and saving plots)
evaluate(model=model, data=data, params=hp, dirs=dirs, verbose=verbose)
```

The following is how I've tried the integration with Talos:

```
# Imports
import argparse
import numpy as np
import keras as ks
import talos as ta
# and so on ...

from my_functions import load_data, create_model, train

# Load data
data = load_data('./my_data.h5')

params = {'batch_size'                 : [128, 256, 512],
          'loss'                       : ['mae', 'logcosh']}

def talos_model(data, params):
    # Set hyperparameters
    hp = {'epochs'                     : 1000,
          'batch_size'                 : params['batch_size'],
          'loss'                       : params['loss']}

    # Build model
    model = create_model(input_shapes=[data['train']['x_0'].shape[1:], data['train']['x_1'].shape[1:]], params=hp)

    # Train
    history, model = train(model=model, data=data, params=hp)

    # Evaluate (predicting on test set and saving plots)
    evaluate(model=model, data=data, params=hp, dirs=dirs, verbose=verbose)

    return history, model

h = ta.Scan(x=[ data['train']['x_0'], data['train']['x_1'] ], # I'm unsure what to put here
            y=data['train']['y'],
            model=talos_model,
            params=params)

```

However, the validation split seems to fail because the data is not structured as Talos expects it to. Here is the traceback:

```
Using TensorFlow backend.
Traceback (most recent call last):
  File "main.py", line 102, in <module>
    grid_downsample=0.1)
  File "/home/ffaye/miniconda3/envs/py3/lib/python3.6/site-packages/talos/scan/Scan.py", line 166, in __init__
    self._null = self.runtime()
  File "/home/ffaye/miniconda3/envs/py3/lib/python3.6/site-packages/talos/scan/Scan.py", line 170, in runtime
    self = scan_prepare(self)
  File "/home/ffaye/miniconda3/envs/py3/lib/python3.6/site-packages/talos/scan/scan_prepare.py", line 60, in scan_prepare
    self = validation_split(self)
  File "/home/ffaye/miniconda3/envs/py3/lib/python3.6/site-packages/talos/utils/validation_split.py", line 18, in validation_split
    random_shuffle(self)
  File "/home/ffaye/miniconda3/envs/py3/lib/python3.6/site-packages/talos/utils/validation_split.py", line 42, in random_shuffle
    self.x = self.x[random_index]
TypeError: only integer scalar arrays can be converted to a scalar index
```

**Questions:** 

1. How can I input my data in a way that makes sense to Talos (preferably without rewriting all my functions)? What are the rules for what can be the arguments for `talos_model`?
2. How can I specify that I would like to use my `[ data['val'][x_0], data['val'][x_1] ], data['val'][y]` as validation data, instead of Talos making the split from my training data?

**Other remarks** (forgive me if there are known issues, or non-issues):
1. In `index.rst`, `reduction_metric` is not explained anywhere.
2. If `grid_downsample` is too low a Python `IndexError` will be thrown. Maybe it would be better to have a Talos error message explaining what is happening?
3. Thank you very much for writing this amazing piece of software! I really hope my issues can be resolved, so that I can start using it! :)

**Comment by mikkokotila** [comment]
Thanks a lot for the kind words :) Also, sorry for the delay in coming to this.

As you suggest it is related with #132 and the fix thereof. But your case is different and broader. 

**Regarding validation split**, (question 1) currently there is no option to input multiple arrays (which is the #132 case and the fix thereof). But that will deal with just the aspect of being able to pass a list of arrays, and might not resolve your case specifically. To say about that, I'd have to see first what is inside create_model(), train(), and evaluate() in your code. (question 2) The validation split itself you can handle through Scan() where you have the option for inputting x_val and y_val as argument. When you do that, there is no other splitting involved.

Thanks for the suggestions. Once 0.4.5 gets to pypi which should happen in the next few days, I'll do a full pass on the manual to make sure it's 100% up-to-date. 

**So what is reduction_metric?** It's the metric (e.g. 'val_acc') the reduction is performed based on. For example, when the optimization algorithm is spearman rank order, the correlation is performed "against" reduction_metric.

**Comment by frederikfaye** [comment]
All right, thank you for the answer! 

For now, I think I will try out scikit-optimize, which is hopefully a bit more flexible w.r.t. to inputs, but I will definitely keep an eye on this project in the future. 

I think scikit-optimize's approach (as I currently understand it) of not fiddling with the inputs/outputs of the model at all, is nice and simple. There (it seems) you simply define a function that takes params from a set search space, and returns any real number (which could be the validation loss of some custom metric) that the minimizer then attempts to minimize by inputting different params. 
Aside from the train_val_split functionality in Talos, what is the reason that the `Scan` method has to know anything about what the data (`x,y`) is? Is it integral to some core functionality of Talos? Is it for instance used when reducing the parameter space?

PS. Please take the above both as (hopefully) constructive critique and as an expression of me wanting to understand how Talos works, and what it does fundamentally different from e.g. scikit-optimize.

**Comment by mikkokotila** [comment]
Related with #132

**Comment by fgvenegas** [comment]
When this is going to be in master? I want to use it in ML-Engine but i can install a version over 0.4.5 and a I need the v.0.4.8. Thanks

**Comment by mikkokotila** [comment]
@fgvenegas 

Why not you do: 

```
pip install -U git+https://github.com/autonomio/talos@daily-dev
```
You will then end up with v.0.4.8

**Comment by fgvenegas** [comment]
@mikkokotila Maybe I'm, but to install a library in ML-Engine you have to specify it like this:
```
REQUIRED_PACKAGES = ['Keras>=2.2.4',  'tensorflow-gpu==1.11']
```
So, in that case I only can install v0.4.5

**Comment by mikkokotila** [comment]
Ah ok, I get it now. Let me look into this and report back later today. I think there is nothing stopping us from pushing to production up until v.0.4.8.
