### ISSUE TITLE
ValueError in the middle of an experiment with custom metric

### ISSUE THREAD

**Issue by aclyde11** [autonomio/talos#179]
After completing 16 runs of ~500, I get this strange value error. I have defined an r2 metric function which works with any of my Keras models. I cannot figure out this strange error. If I checked the log csv, all prior runs have been logged correct and have seemingly correct numbers.

```
Traceback (most recent call last):
  File "RNAseqToSnp.py", line 342, in <module>
    snp_snp_gridsearch(args)
  File "/raid/aclyde11/Benchmarks/Pilot1/RNAseqToSnp/RnaToSnpGridSearch.py", line 181, in snp_snp_gridsearch
    experiment_no='1', debug=True, print_params=True)
  File "/home/aclyde11/scratch-area/Benchmarks/venv/local/lib/python2.7/site-packages/talos/scan/Scan.py", line 163, in __init__
    self._null = self.runtime()
  File "/home/aclyde11/scratch-area/Benchmarks/venv/local/lib/python2.7/site-packages/talos/scan/Scan.py", line 168, in runtime
    self = scan_run(self)
  File "/home/aclyde11/scratch-area/Benchmarks/venv/local/lib/python2.7/site-packages/talos/scan/scan_run.py", line 20, in scan_run
    self = scan_round(self)
  File "/home/aclyde11/scratch-area/Benchmarks/venv/local/lib/python2.7/site-packages/talos/scan/scan_round.py", line 64, in scan_round
    self = reduce_run(self)
  File "/home/aclyde11/scratch-area/Benchmarks/venv/local/lib/python2.7/site-packages/talos/reducers/reduce_run.py", line 16, in reduce_run
    self = reduce_prepare(self)
  File "/home/aclyde11/scratch-area/Benchmarks/venv/local/lib/python2.7/site-packages/talos/reducers/reduce_prepare.py", line 22, in reduce_prepare
    self.param_table.insert(0, self.reduction_metric, self.data[self.reduction_metric])
  File "/home/aclyde11/scratch-area/Benchmarks/venv/local/lib/python2.7/site-packages/pandas/core/frame.py", line 3222, in insert
    allow_duplicates=allow_duplicates)
  File "/home/aclyde11/scratch-area/Benchmarks/venv/local/lib/python2.7/site-packages/pandas/core/internals.py", line 4338, in insert
    raise ValueError('cannot insert {}, already exists'.format(item))
ValueError: cannot insert val_r2, already exists

```

```
def snp_snp_gridsearch_model(x_train, y_train, x_val, y_val, params):
    x_input = Input(shape=(x_train.shape[1],))
    x = Dense(params['first_neuron'], activation=params['activation'], kernel_initializer=params['kernel_initializer'])(
        x_input)
    layer = Dropout(params['dropout'])(x)
    encoded = Dense(params['encoded_dim'], activation=params['activation'],
                    kernel_initializer=params['kernel_initializer'])(x)

    x = Dense(params['first_neuron'], activation=params['activation'], kernel_initializer=params['kernel_initializer'])(
        encoded)
    decoded = Dense(x_train.shape[1], activation=params['last_activation'],
                    kernel_initializer=params['kernel_initializer'])(x)

    model_auto = Model(inputs=x_input, outputs=decoded)
    print(gpu_nums)
    if gpu_nums > 1:
        model_auto = multi_gpu_model(model_auto, gpus=gpu_nums)
    model_auto.compile(loss=params['auto_losses'], optimizer=params['optimizer'](lr=params['lr']), metrics=['acc', r2])

    history = model_auto.fit(x_train, y_train, validation_data=[x_val, y_val], epochs=params['epochs'],
                             batch_size=params['batch_size'], verbose=0)

    return history, model_auto


def snp_snp_gridsearch_params():
    params = {'first_neuron': (1500, 2000, 2),
              'batch_size': (100, 400, 3),
              'epochs': (10, 50, 3),
              'dropout': (0, 0.3, 3),
              'kernel_initializer': ['uniform', 'normal'],
              'encoded_dim': [500, 1000, 1500],
              'auto_losses': ['mse', 'kullback_leibler_divergence', 'categorical_crossentropy'],
              'optimizer': [keras.optimizers.adam, keras.optimizers.SGD],
              'lr': [0.001, 0.01, 0.1],
              'activation': ['sigmoid', 'relu'],
              'last_activation': ['sigmoid', 'relu']}
    return params


def snp_snp_gridsearch(args):
    global gpu_nums
    gpu_nums = args.num_gpus
    loader = DataLoader(args.data_path, args)
    y, _ = loader.load_aligned_snps_rnaseq(use_reduced=True, align_by=args.reduce_snps)

    print(y.tail())
    print(y.describe())
    y = np.array(y, dtype=np.float32)
    if args.y_scale == 'max1':
        y = np.minimum(y, np.ones(y.shape))
    elif args.y_scale == 'scale':
        print("roubust scaling")
        scaler = preprocessing.MinMaxScaler()
        shape = y.shape
        y = scaler.fit_transform(y)
    print("Procressed y:")

    x = np.array(y, dtype=np.float32)
    y = np.array(y, dtype=np.float32)

    x_train, x_val, y_train, y_val = train_test_split(x, y, test_size=0.2)

    t = ta.Scan(x_train, y_train, x_val=x_val, y_val=y_val,
                params=snp_snp_gridsearch_params(),
                model=snp_snp_gridsearch_model,
                grid_downsample=0.01,
                reduction_metric='val_r2',
                reduction_method='correlation',
                dataset_name="SNP_Autoencoder",
                experiment_no='1', debug=True, print_params=True)
    r = ta.Reporting("snp_autoencoder.csv")
```

**Comment by mikkokotila** [comment]
It refers to line 181 in RnaToSnpGridSearch.py. What's happening there?

`File "/raid/aclyde11/Benchmarks/Pilot1/RNAseqToSnp/RnaToSnpGridSearch.py", line 181, in snp_snp_gridsearch`

**Comment by aclyde11** [comment]
I included the functions above, which is ta.Scan(). The error is happening in Talos
  File "/home/aclyde11/scratch-area/Benchmarks/venv/local/lib/python2.7/site-packages/talos/reducers/reduce_prepare.py", line 22, in reduce_prepare
    self.param_table.insert(0, self.reduction_metric, self.data[self.reduction_metric])

**Comment by mikkokotila** [comment]
Can you try without statistical reduction i.e remove from your Scan() the following: 

```
reduction_metric='val_r2',
reduction_method='correlation',
```
Let's see if that works, which will identify the source of the problem to have to do with the way a custom metric would be handled in reduction (which is very likely the only issue here. That should be easy to fix.

**Comment by aclyde11** [comment]
I ran this, but it caused the reporting results to be off. When I run without any custom metrics it seems to work fine.


```
ta.Scan(x_train, y_train, x_val=x_val, y_val=y_val,
                params=snps_from_rnaseq_params(),
                model=rna_snp_pt_gridsearch,
                grid_downsample=0.1,
                reduction_metric='val_r2',
                dataset_name="RNA Autoencoder pretained snp 'ENSG00000181143', 'ENSG00000145113', 'ENSG00000127914', 'ENSG00000149311'",
                experiment_no='1', debug=True, print_params=True)

```

produced a table where all the headings are wrong:
```
round_epochs,val_acc,r2,loss,acc,val_loss,val_r2,dropout,kernel_initializer,first_neuron,lr,batch_size,last_activation,activation,epochs,auto_losses,encoded_dim,optimizer
30,0.0009868420908644207,-0.6940937965725864,1.5713749124486809,0.0013984863458776815,1.5580697216485675,-0.6852260108448958,0.19999999999999998,normal,2000,325,sigmoid,relu,mse,500,30,0.001,<class 'keras.optimizers.SGD'>
30,0.0,-0.06117733305871153,1.050414535100227,0.0,1.0466488873291957,-0.04934450160515936,0.19999999999999998,normal,3000,325,relu,sigmoid,mse,500,30,1.0,<class 'keras.optimizers.Adam'>
10,0.0,-0.22330016052695473,0.6943834601518707,0.0,0.6916910868726278,-0.124912670568416,0.0,uniform,3000,100,sigmoid,relu,mae,2000,10,0.1,<class 'keras.optimizers.SGD'>
10,0.0,-0.021660796471746707,1.0004304707560268,0.0,0.9982786290347576,-0.0003427976840420773,0.09999999999999999,normal,2000,250,sigmoid,relu,mse,500,10,0.1,<class 'keras.optimizers.Adam'>
10,0.0,-0.4863396825936328,0.8720775461973583,0.00024679171952059507,0.8620093786402753,-0.4671794352562804,0.09999999999999999,normal,3000,250,relu,sigmoid,mae,1000,10,0.1,<class 'keras.optimizers.SGD'>
30,0.00032894736489795734,-0.33370781199796373,0.8732570537555057,0.0,0.866916883442747,-0.28448471583818136,0.09999999999999999,uniform,2000,175,relu,sigmoid,mse,2000,30,0.1,<class 'keras.optimizers.SGD'>
```

**Comment by mikkokotila** [comment]
See #146 as it's resolved and probably the same issue you are having. The fix is very simple, wrap params inside `OrderedDict` from after `from collections import OrderedDict`. 

Also do make sure that you get 0.4.6 or 0.4.7 `from print(talos.__version__)`.

Let's see where that lands you :)

**Comment by Joe310** [comment]
I ran into this same problem when trying to use the categorical_accuracy metric.  I was able to fix it by adding categorical_accuracy and val_categorical_accuracy to the list returned by metric_names() in reducers.reduce_prepare(). 

You may want to update metric_names() to include all the metrics in keras.metrics or add a check to ensure the self.reduction_metric is actually included in the list returned by metric_names().

**Comment by mikkokotila** [comment]
Closing here as these issues are no longer relevant in the current versions of Talos.
