### ISSUE TITLE
ValueError: ('Some keys in session_kwargs are not supported at this time: %s', dict_keys(['lr']))

### ISSUE THREAD

**Issue by davide1993** [autonomio/talos#180]
why if I use lr_normalizer into compile I get the error in the title?
Whitout it everithing works

```
 model.compile( optimizer=params['optimizer'],
                      lr=lr_normalizer(params['lr'],params['optimizer']),
                      loss=params['losses'],
                      metrics=['acc',fmeasure_acc,precision_acc, recall_acc])
```
output:ValueError: ('Some keys in session_kwargs are not supported at this time: %s', dict_keys(['lr']))

```
 model.compile( optimizer=params['optimizer'],
    
                      loss=params['losses'],
                      metrics=['acc',fmeasure_acc,precision_acc, recall_acc])
```
works

**Comment by mikkokotila** [comment]
See from the [corresponding section in the docs](https://autonomio.github.io/docs_talos/#lr-normalizer) for how to use lr_normalizer. It will not work in the way you are trying to call it now. Also note that you will have to have the actual optimizer function e.g. `adam` and not string` 'adam' ` as you are basically doing `adam(lr_normalizer...)` because Keras only supports setting learning rate directly with optimizer and not through model.compile().

**Comment by davide1993** [comment]
```
model.compile(loss='binary_crossentropy',
              optimizer=params['optimizer'](lr_normalizer(params['lr'], params['optimizer'])),
              metrics=['accuracy'])

```
now output:

```
Using TensorFlow backend.

  0%|          | 0/1728 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/davide/.local/lib/python3.6/site-packages/talos/scan/scan_round.py", line 32, in scan_round
    _hr_out, self.keras_model = ingest_model(self)
  File "/home/davide/.local/lib/python3.6/site-packages/talos/model/ingest_model.py", line 10, in ingest_model
    self.round_params)
  File "/home/davide/git/bankrupty/src/australianDataset.py", line 170, in getCNNModel
    optimizer=params['optimizer'](lr_normalizer(params['lr'], params['optimizer'])),
TypeError: 'str' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/davide/git/bankrupty/src/main.py", line 465, in <module>
    talosOptimizer(dataset)
  File "/home/davide/git/bankrupty/src/main.py", line 305, in talosOptimizer
    grid_downsample=0.01)# da settare tra 0 e 1 per evitare grid search, + vicino allo zero meno esempi sono presi
  File "/home/davide/.local/lib/python3.6/site-packages/talos/scan/Scan.py", line 163, in __init__
    self._null = self.runtime()
  File "/home/davide/.local/lib/python3.6/site-packages/talos/scan/Scan.py", line 168, in runtime
    self = scan_run(self)
  File "/home/davide/.local/lib/python3.6/site-packages/talos/scan/scan_run.py", line 20, in scan_run
    self = scan_round(self)
  File "/home/davide/.local/lib/python3.6/site-packages/talos/scan/scan_round.py", line 37, in scan_round
    raise TalosReturnError("Make sure that input model returns 'out, model' where out is history object from model.fit()")
talos.utils.exceptions.TalosReturnError: Make sure that input model returns 'out, model' where out is history object from model.fit()
```

**Comment by mikkokotila** [comment]
What is inside `params['optimizer']`?

**Comment by davide1993** [comment]
```
         p = {'lr': (0.5, 10, 10),
               'first_neuron':[8,16,32,64],
               'hidden_layers': [1,2, 3, 4,5,6],
               'batch_size': [16,32,64,128],
               'epochs': [100,200,300],
               'dropout': (0, 0.70, 10),
               'weight_regulizer': [None],
               'emb_output_dims': [None],
               'optimizer': ['Adam', 'Nadam', 'RMSprop'],
               'losses': [binary_crossentropy],
               'activation': [relu,elu],
               'last_activation': [sigmoid]}

```

**Comment by mikkokotila** [comment]
It is because your optimizers are in the wrong form. You have to do:

`'optimizer': [Adam, Nadam, RMSprop]`

**Comment by davide1993** [comment]
now it works thanks

**Comment by roozan-hash** [comment]
history3 = model3.fit(X_train, y_train,
                      batch_size = batch_size,
                      epochs = training_epochs,
                      validation_data=(X_cv, y_cv))
