### ISSUE TITLE
Chrash in epoch_entropy when using keras validation_freq

### ISSUE THREAD

**Issue by JohanMollevik** [autonomio/talos#263]
When using the new keras feature validation_freq to not run validation on every epoch talos chrashes in epoch_entropy

print of history.history and stack trace:
{'loss': [0.25765683741535583, 0.19005843383075188], 'acc': [0.909375, 0.9390625], 'val_loss': [0.14024672794768017], 'val_acc': [0.9515625]}
Traceback (most recent call last):
  File "./run.py", line 354, in <module>
    ,clear_tf_session=True
  File "/opt/conda/lib/python3.6/site-packages/talos-0.5.0-py3.6.egg/talos/scan/Scan.py", line 185, in __init__
  File "/opt/conda/lib/python3.6/site-packages/talos-0.5.0-py3.6.egg/talos/scan/Scan.py", line 190, in runtime
  File "/opt/conda/lib/python3.6/site-packages/talos-0.5.0-py3.6.egg/talos/scan/scan_run.py", line 20, in scan_run
  File "/opt/conda/lib/python3.6/site-packages/talos-0.5.0-py3.6.egg/talos/scan/scan_round.py", line 49, in scan_round
  File "/opt/conda/lib/python3.6/site-packages/talos-0.5.0-py3.6.egg/talos/metrics/entropy.py", line 44, in epoch_entropy
  File "/opt/conda/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py", line 2550, in entropy
    raise ValueError("qk and pk must have same length.")
ValueError: qk and pk must have same length.

**Comment by mikkokotila** [comment]
This has to do with the feature where we are capturing the entropy of the epoch validation variation and pk refers to the base that is used for taking KL divergence as opposed to normal shannon entropy. It seems that  `validation_freq` creates an invariable length history object.

**Comment by mikkokotila** [comment]
Ah ok I see from the print out how it plays out.

**Comment by JohanMollevik** [comment]
I made a pull request that prevents the entropy capture in these cases avoiding the chrash, is this a reasonable way to fix this?

I was going to add a test but I did not figure out a good place for it in the new test organisation.

**Comment by mikkokotila** [comment]
I've completely re-created learning entropy in a way that makes sense for all imaginable cases. Later today or latest tomorrow I'd be pushing a major overhaul of Talos to daily-dev. Entropy included. Will continue testing and documenting today. This is part of a sincere wish I have to completely standardize everything about Talos architecture. I think too many open source projects end up being a collection of features rather than well thought of system. Given the often critical nature of the topics that Talos is used for, I think it's really important we represent the latter of the two approaches.

**Comment by JohanMollevik** [comment]
Ok, makes sense. I will test the new system once you have pushed

**Comment by mikkokotila** [comment]
This have been handled sometime ago, so closing here.
