### ISSUE TITLE
Unable to run Autoscan

### ISSUE THREAD

**Issue by KalidindiMounika** [autonomio/talos#438]
autom8.start(x=x_train, y=y_train, x_val=x_val, y_val=y_val,fraction_limit=0.000001) is throwing below error:
Using TensorFlow backend.
Traceback (most recent call last):
  File "/home/practice/HyperOpt/python3.6/lib/python3.6/site-packages/talos/autom8/autoscan.py", line 38, in start
    kwargs['params']
KeyError: 'params'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mytest.py", line 16, in <module>
    y_val=y_val)
  File "/home/practice/HyperOpt/python3.6/lib/python3.6/site-packages/talos/autom8/autoscan.py", line 54, in start
    **kwargs)
  File "/home/practice/HyperOpt/python3.6/lib/python3.6/site-packages/talos/scan/Scan.py", line 196, in __init__
    self._runtime()
  File "/home/practice/HyperOpt/python3.6/lib/python3.6/site-packages/talos/scan/Scan.py", line 201, in _runtime
    self = scan_run(self)
  File "/home/practice/HyperOpt/python3.6/lib/python3.6/site-packages/talos/scan/scan_run.py", line 9, in scan_run
    self = scan_prepare(self)
  File "/home/practice/HyperOpt/python3.6/lib/python3.6/site-packages/talos/scan/scan_prepare.py", line 8, in scan_prepare
    self._experiment_log = initialize_log(self)
  File "/home/practice/HyperOpt/python3.6/lib/python3.6/site-packages/talos/scan/scan_utils.py", line 9, in initialize_log
    os.mkdir(path + '/' + self.experiment_name)
TypeError: must be str, not int

Kindly help me in resolving the issue

**Comment by mikkokotila** [comment]
Can you share your parameter dictionary.

**Comment by KalidindiMounika** [comment]
I am able to run the Auto scan but now best model after scan ,by using the  command
"best_model = scan_object.best_model(metric=metricVal, asc=ascVal)"  gives me different result each time and in certain cases , I am getting prediction results as nan

**Comment by KalidindiMounika** [comment]
I am able to run the Auto scan but now best model after scan gives me different result each time by using the  command
"best_model = scan_object.best_model(metric=metricVal, asc=ascVal)" and in certain cases , I am getting prediction results as nan

**Comment by mikkokotila** [comment]
To be able to help you, I need to have your params dictionary, your input model, and your Talos commands.
