### ISSUE TITLE
Adam is not supported by lr_normalizer

### ISSUE THREAD

**Issue by windowshopr** [autonomio/talos#477]
Python 3.6, Windows 10, all dependencies are up to date. I have the following code:

```
def the_model(x_train, y_train, x_val, y_val, params):

    model = Sequential()

    model.add(Dense(params['first_neuron'], input_dim=x_train.shape[1],
                    activation=params['activation'],
                    kernel_initializer=params['kernel_initializer']))
    
    model.add(Dropout(params['dropout']))

    model.add(Dense(params['last_neuron'], activation=params['last_activation'],
                    kernel_initializer=params['kernel_initializer']))
    
    model.compile(loss=params['losses'],
                  optimizer=params['optimizer'](lr_normalizer(params['lr'], params['optimizer'])),
                  metrics=['accuracy', talos.utils.metrics.f1score])
    
    history = model.fit(x_train, y_train, 
                        validation_data=[x_val, y_val],
                        batch_size=params['batch_size'],
                        callbacks=[early_stopper(params['epochs'], mode='moderate')], # talos.utils.live(), 
                        epochs=params['epochs'],

                        verbose=0)

    return history, model

# then we can go ahead and set the parameter space
p = {'first_neuron':[32, 64, 128],
     'lr':[1],   # Here is the learning rate
     'hidden_layers':[1, 2, 3],
     'last_neuron':[1],
     'batch_size': [32, 64, 128, 256],
     'epochs': [training_runs],
     'dropout': [0, 0.25, 0.5],
     'shapes':['brick', 'funnel', 'triangle'],
     'kernel_initializer': ['uniform','normal'],
     'weight_regulizer':[None],
     'emb_output_dims': [None],
     'optimizer': ['Adam'],
     'losses': ['binary_crossentropy'],
     'activation':['relu', 'elu'],
     'last_activation': ['sigmoid']}

# and run the experiment
t = talos.Scan(x=X_SET, y=Y_SET, 
    model=the_model, 
    params=p, 
    val_split=test_size, 
    experiment_name='stock_1_day_classifier', 
    round_limit=4, 
    clear_session='tf')
```

And get the error mentioned in the title. How does one get this working? What am I missing? I think I'm following the user guide as directed and the example scripts weren't clear so I'm wondering what I might need to fix. Thanks!

**Comment by mikkokotila** [comment]
You have to use the actual function as input. So import it first, and then just the imported function. So instead of `'Adam'` you end up with `Adam`.

**Comment by windowshopr** [comment]
@mikkokotila  I tried that as well but still having issues.

I have tried importing the function as `from keras.optimizers import Adam` and get this error:

`ValueError: ('Could not interpret optimizer identifier:', <class 'keras.optimizers.Adam'>)`

...and I tried importing like:

`from tensorflow.keras.optimizers import Adam`

and get:

`ValueError: ('Could not interpret optimizer identifier:', <class 'tensorflow.python.keras.optimizer_v2.adam.Adam'>)`

I'm running Tensorflow 2.1 with eager execution disabled. Have tried enabling it too but get the same thing. Any other ideas? Thanks!

**Comment by windowshopr** [comment]
@mikkokotila  I just discovered if I use 'adam' instead of 'Adam' it works. I looked at my previous standalone Tensorflow code and had the optimizer defined as 'adam' so I did that and it works. Thanks!!

**Comment by mikkokotila** [comment]
After you import Adam, you must then use it as input like `[Adam]` and not `['Adam']`.

**Comment by windowshopr** [comment]
I should clarify that I did make the change to Adam (from ‘Adam’) and it wasn’t working. I’m at work now but I can post my trace back for the error using Adam as the function a little later tonight. Will advise.

**Comment by windowshopr** [comment]
Hey @mikkokotila 

So here is my updated sections of code and following traceback:

```
from tensorflow.keras.optimizers import Adam
# from keras.optimizers import Adam
```
...

```
# then we can go ahead and set the parameter space
p = {'first_neuron':[32, 64, 128, 256],
     'lr':[1],
     'hidden_layers': [1, 2, 3],
     'last_neuron': [1],
     'batch_size': [64, 128, 256, 512],
     'epochs': [1000],
     'dropout': [0, 0.25, 0.5],
     'shapes': ['brick', 'funnel', 'triangle'],
     'kernel_initializer': ['uniform','normal'],
     'weight_regulizer':['l2', 'l1'],
     'emb_output_dims': [None],
     'optimizer': [Adam] # also tried 'Adam'
     'losses': ['binary_crossentropy'],
     'activation': ['relu', 'elu'],
     'last_activation': ['sigmoid']}

# and run the experiment
t = talos.Scan(x=X_SET, y=Y_SET, 
    model=the_model, 
    params=p, 
    val_split=test_size, 
    experiment_name='1_day_classifier_talos', 
    round_limit=10,
    clear_session='tf')
```

Traceback:

`ValueError: ('Could not interpret optimizer identifier:', <class 'tensorflow.python.keras.optimizer_v2.adam.Adam'>)`

I notice that adam is trying to be mentioned twice???

**Comment by mikkokotila** [comment]
Can you share your input model as well, together with the full trace.

**Comment by windowshopr** [comment]
Will do later tonight again. I’m running it from command prompt too so I’ll clean up the traceback to make it easier to read

**Comment by mikkokotila** [comment]
It's better if you can copy paste the trace from terminal entirely as it is.

**Comment by windowshopr** [comment]
Will do, thanks. Also I’m running tensorflow 2.1 if that matters. Will post code and traceback later tonight

**Comment by windowshopr** [comment]
@mikkokotila  Here is my code with imports, the model definition function, and other sections:

```
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, Dense, GRU, Dropout
from tensorflow.keras.optimizers import RMSprop, Adam

tf.compat.v1.disable_eager_execution()

import talos
from talos.model.early_stopper import early_stopper
from talos.model.normalizers import lr_normalizer
...
...
...
...
# DEFINE OUR TALOS MODEL ARCHITECTURE
# first we have to make sure to input data and params into the function
def the_model(x_train, y_train, x_val, y_val, params):

    model = Sequential()

    model.add(Dense(params['first_neuron'], input_dim=x_train.shape[1],
                    activation=params['activation'],
                    kernel_initializer=params['kernel_initializer']))
    
    model.add(Dropout(params['dropout']))

    model.add(Dense(params['last_neuron'], activation=params['last_activation'],
                    kernel_initializer=params['kernel_initializer']))
    
    model.compile(loss=params['losses'],
                  optimizer=params['optimizer'](lr_normalizer(params['lr'], params['optimizer'])),
                  # Also tried just (lr_normalizer(params['lr'], params['optimizer']))
                  metrics=['accuracy', talos.utils.metrics.f1score])
    
    history = model.fit(x_train, y_train, 
                        validation_data=[x_val, y_val],
                        batch_size=params['batch_size'],
                        callbacks=[early_stopper(params['epochs'], mode='moderate')], # talos.utils.live(), 
                        epochs=params['epochs'],
                        verbose=0)
    return history, model


# then we can go ahead and set the parameter space
p = {'first_neuron':[32, 64, 128, 256],
     'lr':[1],
     'hidden_layers': [2, 3, 4],
     'last_neuron': [1],
     'batch_size': [64, 128, 256, 512],
     'epochs': [training_runs],
     'dropout': [0, 0.25, 0.5],
     'shapes': ['brick', 'funnel', 'triangle'],
     'kernel_initializer': ['uniform','normal'],
     'weight_regulizer':['l1_l2', 'gaussian', 'l1', 'l2'],
     'emb_output_dims': [None],
     'optimizer': [Adam],    #, 'Adam'],
     'losses': ['binary_crossentropy'],
     'activation': ['relu', 'elu'],
     'last_activation': ['sigmoid']}



# and run the experiment
t = talos.Scan(x=X_SET, y=Y_SET, 
    model=the_model, 
    params=p, 
    val_split=test_size, 
    experiment_name='1_day_classifier_talos', 
    round_limit=100, 
    clear_session='tf')
```

...and the traceback

```
  0%|                                                                                          | 0/100 [00:00<?, ?it/s]WARNING: Logging before flag parsing goes to stderr.
W0304 21:58:42.907507 210852 deprecation.py:506] From C:\Users\windowshopr\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\keras\initializers.py:143: calling RandomNormal.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Traceback (most recent call last):
  File "2_classifier_train_talos.py", line 336, in <module>
    clear_session='tf')
  File "C:\Users\windowshopr\AppData\Local\Programs\Python\Python36\lib\site-packages\talos\scan\Scan.py", line 196, in __init__
    scan_run(self)
  File "C:\Users\windowshopr\AppData\Local\Programs\Python\Python36\lib\site-packages\talos\scan\scan_run.py", line 26, in scan_run
    self = scan_round(self)
  File "C:\Users\windowshopr\AppData\Local\Programs\Python\Python36\lib\site-packages\talos\scan\scan_round.py", line 19, in scan_round
    self.model_history, self.round_model = ingest_model(self)
  File "C:\Users\windowshopr\AppData\Local\Programs\Python\Python36\lib\site-packages\talos\model\ingest_model.py", line 10, in ingest_model
    self.round_params)
  File "2_classifier_train_talos.py", line 293, in the_model
    optimizer=params['optimizer'](lr_normalizer(params['lr'], params['optimizer'])),
  File "C:\Users\windowshopr\AppData\Local\Programs\Python\Python36\lib\site-packages\talos\model\normalizers.py", line 27, in lr_normalizer
    raise TalosModelError(str(optimizer) + " is not supported by lr_normalizer")
talos.utils.exceptions.TalosModelError: <class 'tensorflow.python.keras.optimizer_v2.adam.Adam'> is not supported by lr_normalizer
  0%|                                                                                          | 0/100 [00:00<?, ?it/s]
```

Any help would be greatly appreciated on things to try. Would love to get the learning rate in there for training. Thanks again.

**Comment by mikkokotila** [comment]
Ah ok, I think this has to do with mismatch between your Talos version and the tensorflow/keras versions. 

What do you get with `talos.__version__` and `tensorflow.__version__`?

**Comment by windowshopr** [comment]
@mikkokotila 

print(tf.__version__)
print(tf.keras.__version__)
print(pd.__version__)
print(talos.__version__)

...gives me

1.14.0
2.2.4-tf
0.25.1
0.6.4

...which is weird because I just did the upgrade to tf version 2.1. I'm going to try the upgrade again tonight and see if that fixes it?

**Comment by windowshopr** [comment]
@mikkokotila  I now have Tensorflow 2.1 re-installed, but still same issue :(

**Comment by windowshopr** [comment]
Ok good news! I followed this post about [451](https://github.com/autonomio/talos/issues/451)

And got it workin! Just uninstalled tensorflow, used the `pip install git+https://github.com/autonomio/talos@1.0` command, and she started workin! Thanks @mikkokotila 

Closing now
