### ISSUE TITLE
Restore Function Gives "EmptyDataError: No columns to parse from file" - LSTM

### ISSUE THREAD

**Issue by windowshopr** [autonomio/talos#480]
```
Python 3.6, Windows 10,

tensorflow==2.1.0
pandas==0.25.1
talos==1.0.0
```
(I realize the Talos version MAY be out of date, however I found a pip install url link in one of the past issue pages that finally got this tool to work for me, so I'm hesitant to change it, for now.)

I've created an GRU/LSTM scan object that works that I found by browsing through the other issues related to LSTM devlopment and Talos. It works fine, only what I'm trying to do now is Deploy the scan package to its .zip file, Restore the model from said .zip and then Predict on a test set.

I get the following traceback:

```
100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:07<00:00,  7.93s/it]
Scanning is complete. Check your outputted .csv file. Pick the best "val_accuracy".
Evaluating the model...
mean : 0.03
 std : 0.01

Making deployment package...
Deploy package talos_classifier_deployment have been saved.
data is not 2d, dummy data written instead.

Restoring package...
Traceback (most recent call last):
  File "lstm_talos.py", line 255, in <module>
    model = Restore('talos_classifier_deployment.zip')
  
File "C:\Users\windowshopr\AppData\Local\Programs\Python\Python36\lib\site-packages\talos\commands\restore.py", line 41, in __init__
    self.x = pd.read_csv(self.file_prefix + '_x.csv', header=None)
  
File "C:\Users\windowshopr\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\io\parsers.py", line 685, in parser_f
    return _read(filepath_or_buffer, kwds)
  
File "C:\Users\windowshopr\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\io\parsers.py", line 457, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  
File "C:\Users\windowshopr\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\io\parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  
File "C:\Users\windowshopr\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\io\parsers.py", line 1135, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  
File "C:\Users\windowshopr\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\io\parsers.py", line 1917, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  
File "pandas\_libs\parsers.pyx", line 545, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
```

So I look in the .zip file and sure enough, the X/Features .csv file has nothing in it. Wondering why that would be? I've attached what my Talos section looks like, and the function that creates my 3D data for the LSTM:

```
# A function to get a set of X's and Y's for training
def create_dataset(X, y, time_steps=1): # Not really 1 if defined below
    Xs, ys = [], []
    for i in range(len(X) - time_steps):
        v = X[i:(i + time_steps)] # v = first 10 rows of X set
        Xs.append(v) # Append those 10 rows to your Xs list
        ys.append(y[i + time_steps]) # Append their corresponding labels to Ys list, then continue
    return np.array(Xs), np.array(ys)

# How many days/rows to "look back"
time_steps = 10

# reshape to [samples, time_steps, n_features]
x_train, y_train = create_dataset(train_scaled.to_numpy(), train_scaled.iloc[:,-1].to_numpy(), time_steps)
x_test, y_test = create_dataset(test_scaled.to_numpy(), test_scaled.iloc[:,-1].to_numpy(), time_steps)



# DEFINE OUR TALOS MODEL SAMPLE ARCHITECTURE
def the_model(x_train, y_train, x_val, y_val, params):

    model = Sequential()

    model.add(GRU(params['first_neuron'], 
                    input_shape=(x_train.shape[1], x_train.shape[2])))
    
    model.add(Dropout(params['dropout']))

    hidden_layers(model, params, 1)

    model.add(Dense(params['last_neuron']))
    
    model.compile(loss=params['losses'],
                  optimizer=params['optimizer'](lr=lr_normalizer(params['lr'], params['optimizer'])))
    
    history = model.fit(x_train, y_train, 
                        validation_data=[x_val, y_val],
                        batch_size=params['batch_size'],
                        callbacks=[early_stopper(params['epochs'], mode='moderate')],
                        epochs=params['epochs'],
                        verbose=0)

    return history, model


# then we can go ahead and set the parameter space
p = {'first_neuron':[10],
     'lr':[1],
     'hidden_layers': [1],
     'last_neuron': [1],
     'batch_size': [64],
     'epochs': [1000],
     'dropout': [0], 
     'shapes': [0.5], 
     'optimizer': [Adam], # RMSprop, Adagrad, Adadelta
     'losses': ['mse'], # binary_crossentropy
     'activation': ['relu']} #, 'elu'],


# and run the experiment
t = talos.Scan(x=x_train, y=y_train,
    x_val=x_test, y_val=y_test,
    model=the_model, 
    params=p, 
    experiment_name='talos_stuff', 
    round_limit=1,      
    save_weights=True,   
    reduction_metric='loss',
    clear_session=True)

print('Scanning is complete.')

print('Evaluating the model...')
e = talos.Evaluate(t)
evaluation = e.evaluate(x_test,
                        y_test,
                        model_id=None, 
                        task='continuous',
                        shuffle=False, 
                        print_out=True,
                        metric='loss', asc=False)

print('Making deployment package...')
model = talos.Deploy(t, "talos_classifier_deployment", 
                #metric="val_loss", asc=True)
                metric="loss", asc=False)


print('Restoring package...') 
model = Restore('talos_classifier_deployment.zip')
y_preds = model.model.predict(x_test)
```

**Comment by mikkokotila** [comment]
Try changing `validation_data=[x_val, y_val]` to `validation_data=(x_val, y_val)`. Closing this as resolved, feel free to open new issue if anything.

**Comment by mybooc** [comment]
Also ran into this. The example above is using 3D data. This works fine in Keras but Talos (1.0.2) does not fully support this. Deploy throws a message: 'data is not 2d, dummy data written instead'.
