### ISSUE TITLE
Talos Scan() gives InvalidArgumentError at 64% with Function call stack: test_function

### ISSUE THREAD

**Issue by lmvanpoppel** [autonomio/talos#507]
First of all, thanks very much for developing this tool, it is very intuitive and easy to use for people to whom machine learning is new (like me). I hope you can help me with the following. I don't understand why the error occurs at 64% of the scan? 

**#### 1) Confirm the below - Confirmed; Python 3.7.6**
**#### 2) Include the output of:**

`talos.__version__`
1.0.0

**#### 3) Explain clearly what you are trying to achieve**

I am using Talos to determine certain hyperparameters for my LSTM model. My input are subject matrices of [features x timesteps] and my output per subject is binary '1' or '0'. 

I want to have my model optimized to not predict false positives (the subject is either sick (1) or not sick(0), it is crucial that the model doesn't falsely predict sickness)

In the Scan I therefor use the reduction_metric 'val_precision' 

**#### 4) Explain what you have already tried**

I used the Talos examples to create a search, I ran the Scan function. This all went well until the scan was at 64% and I got this error: 

```
Using TensorFlow backend.
  0%|          | 0/614 [00:00<?, ?it/s]2020-09-28 16:26:18.733017: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-09-28 16:26:18.747796: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fcd7fe417c0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-09-28 16:26:18.747809: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
 64%|██████▎   | 390/614 [1:49:42<1:14:59, 20.09s/it]Traceback (most recent call last):

  File "/Users/.../Talos_search01", line 142, in <module>
    reduction_metric='val_precision')

  File "/Users/.../opt/anaconda3/lib/python3.7/site-packages/talos/scan/Scan.py", line 196, in __init__
    scan_run(self)

  File "/Users/.../opt/anaconda3/lib/python3.7/site-packages/talos/scan/scan_run.py", line 26, in scan_run
    self = scan_round(self)

  File "/Users/.../opt/anaconda3/lib/python3.7/site-packages/talos/scan/scan_round.py", line 19, in scan_round
    self.model_history, self.round_model = ingest_model(self)

  File "/Users/...l/opt/anaconda3/lib/python3.7/site-packages/talos/model/ingest_model.py", line 10, in ingest_model
    self.round_params)

  File "/Users/.../Talos_search01", line 109, in LSTM_model
    verbose=0)

  File "/Users/.../opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 108, in _method_wrapper
    return method(self, *args, **kwargs)

  File "/Users/.../opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 1133, in fit
    return_dict=True)

  File "/Users/.../opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 108, in _method_wrapper
    return method(self, *args, **kwargs)

  File "/Users/.../opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 1379, in evaluate
    tmp_logs = test_function(iterator)

  File "/Users/.../opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)

  File "/Users/.../opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 814, in _call
    results = self._stateful_fn(*args, **kwds)

  File "/Users/.../opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2829, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access

  File "/Users/.../opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1848, in _filtered_call
    cancellation_manager=cancellation_manager)

  File "/Users/.../opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1924, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))

  File "/Users/...l/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 550, in call
    ctx=ctx)

  File "/Users/...l/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)

InvalidArgumentError:  assertion failed: [predictions must be >= 0] [Condition x >= y did not hold element-wise:] [x (sequential/activation/Sigmoid:0) = ] [[nan][nan][nan]...] [y (Cast_6/x:0) = ] [0]
	 [[{{node assert_greater_equal/Assert/AssertGuard/else/_49/assert_greater_equal/Assert/AssertGuard/Assert}}]] [Op:__inference_test_function_5700163]

Function call stack:
test_function


```
#### 5) Provide a code-complete reference

```

import tensorflow 
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, LSTM, BatchNormalization, Activation
from tensorflow.keras.regularizers import l1_l2
from tensorflow.keras.optimizers import Adam, Nadam, SGD  
from tensorflow.keras.metrics import Accuracy, AUC, FalsePositives, SensitivityAtSpecificity, Precision

import pandas as pd
import numpy as np 
import matplotlib
from matplotlib import pyplot
from scipy.io import loadmat
from sklearn.model_selection import train_test_split

import talos
from talos.utils import lr_normalizer


################
# Prepare Data #
################

# import 2D structure 
dataMatlab = loadmat('LSTM_poorpos.mat');
dataML = dataMatlab.get('LSTM_poorpos');

# define features and targets 
features = dataML[:,:13];
outcomes = dataML[:,13]; # 1 is poor outcome 

# reshape to input matrices and outcome vector
timesteps = 30;
predictors = 13; 
subjects = int(features.shape[0]/timesteps);

x = features.reshape(subjects,timesteps,predictors);
y = outcomes.reshape(subjects,timesteps);
y = y[:,0];
    

# divide data into train and test sets
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.1,stratify=y);
# divide training data into train and validation sets
x_tr,x_val,y_tr,y_val=train_test_split(x_train,y_train,test_size=0.2,stratify=y_train);



def LSTM_model(x_tr, y_tr, x_val, y_val, params):
    
    ##############################
    # Define constant parameters #
    ##############################
    # first LSTM layer 
    input_LSTM = (x_tr.shape[1:])
    # fully connected layer 
    activation_function_FC = 'sigmoid'
    hidden_units_FC = 1
    # compile
    loss_function = 'binary_crossentropy'
    metric1 = 'accuracy'
    metric2 = AUC(name='auc')
    metric3 = Precision(name='precision')
    metric4 = SensitivityAtSpecificity(1, name='sensitivity_at_specificity')
    

    ###############
    # Build model # 
    ###############   
    model = Sequential()
    
    model.add(LSTM(params['hidden_units_LSTM1'], 
                   input_shape=input_LSTM, 
                   activation=params['activation1'],
                   dropout=params['dropout1'], 
                   recurrent_dropout=params['recurrent_dropout1'], 
                   return_sequences=False))
   
    model.add(BatchNormalization())
    model.add(Dense(hidden_units_FC))
    model.add(Activation(activation_function_FC))
   
    
    #################
    # Compile model #
    #################
    
    model.compile(
        loss=loss_function,
        optimizer=params['optimizer'](lr=lr_normalizer(params['lr'], params['optimizer'])),
        metrics=[metric1, metric2, metric3, metric4])
    

    #############
    # Fit model #
    #############
    history = model.fit(x_tr,
                        y_tr,
                        validation_data=(x_val,y_val),
                        batch_size=params['batch_size'],
                        epochs=params['epochs'],
                        verbose=0)
    
   # history object and model are returned
    return history, model


##############
# Parameters # 
##############

p = {'hidden_units_LSTM1':[5,10,15,20,35,50,75,100],
     'activation1':['relu', 'tanh'],      
     'dropout1': (0, 0.8, 4),
     'recurrent_dropout1':(0, 0.8, 4),
     
     'optimizer': [SGD, Adam, Nadam],
     'lr': (0.1, 10, 5),

     'batch_size': [16,32,64,128],
     'epochs': [50,100,150,200],
     }
   
########
# Scan #
########
scan_object = talos.Scan(x=x_tr,
                         y=y_tr,
                         x_val=x_val,
                         y_val=y_val,
                         model=LSTM_model,
                         params=p,
                         experiment_name='Outcome Prediction',
                         fraction_limit=0.01,
                         reduction_metric='val_precision')

```

x = (254,30,13) array of float64 (254 subjects, 30 timesteps, 13 features)
y = (254,) array of float64 (254 binary outcomes for subjects)

example of a subject matrix (30x13)
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/64014642/94534235-6f18f080-0240-11eb-9306-a0d978156c96.png">

---

**Comment by lmvanpoppel** [comment]
Update: I get the same error if I remove the reduction_metric (I did set the fraction limit to 0.001 to do a quick check)
```
File "/Users/.../Talos_search01", line 141, in <module>
    fraction_limit=0.001

  File "/Users/.../opt/anaconda3/lib/python3.7/site-packages/talos/scan/Scan.py", line 196, in __init__
    scan_run(self)

  File "/Users/.../opt/anaconda3/lib/python3.7/site-packages/talos/scan/scan_run.py", line 26, in scan_run
    self = scan_round(self)

  File "/Users/.../opt/anaconda3/lib/python3.7/site-packages/talos/scan/scan_round.py", line 19, in scan_round
    self.model_history, self.round_model = ingest_model(self)

  File "/Users/.../opt/anaconda3/lib/python3.7/site-packages/talos/model/ingest_model.py", line 10, in ingest_model
    self.round_params)

  File "/Users/.../Documenten/BME/Afstuderen/PAC/Python/Talos_search01", line 109, in LSTM_model
    verbose=0)

  File "/Users/.../opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 108, in _method_wrapper
    return method(self, *args, **kwargs)

  File "/Users/.../opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 1133, in fit
    return_dict=True)

  File "/Users/.../opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 108, in _method_wrapper
    return method(self, *args, **kwargs)

  File "/Users/.../opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 1379, in evaluate
    tmp_logs = test_function(iterator)

  File "/Users/.../opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)

  File "/Users/.../opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 814, in _call
    results = self._stateful_fn(*args, **kwds)

  File "/Users/.../opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2829, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access

  File "/Users/.../opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1848, in _filtered_call
    cancellation_manager=cancellation_manager)

  File "/Users/.../opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1924, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))

  File "/Users/.../opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 550, in call
    ctx=ctx)

  File "/Users/.../opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)

InvalidArgumentError:  assertion failed: [predictions must be >= 0] [Condition x >= y did not hold element-wise:] [x (sequential/activation/Sigmoid:0) = ] [[nan][nan][nan]...] [y (Cast_6/x:0) = ] [0]
	 [[{{node assert_greater_equal/Assert/AssertGuard/else/_49/assert_greater_equal/Assert/AssertGuard/Assert}}]] [Op:__inference_test_function_19338]

Function call stack:
test_function
```

**Comment by mikkokotila** [comment]
Is [this](https://stackoverflow.com/questions/57062456/function-call-stack-keras-scratch-graph-error) possible related? Or other similar posts.

**Comment by mikkokotila** [comment]
Closing this due to inactivity, feel free to reopen.
