### ISSUE TITLE
 Failed to build scipy while installing talos

### ISSUE THREAD

**Issue by Mirijam1** [autonomio/talos#551]
I am trying to install talos using `pip install talos`. However I keep getting the errors below: 
```
Building wheels for collected packages: talos, scipy
  Building wheel for talos (setup.py) ... done
  Created wheel for talos: filename=talos-1.0.2-py3-none-any.whl size=54137 sha256=74c6ec62e133d559b2c371c710e7751b17718909a478dbd6ea2a3859322e04cf
  Stored in directory: C:\Users\mirij\AppData\Local\Temp\pip-ephem-wheel-cache-79y_2z_4\wheels\b7\bc\45\2f42ba3131608d45825ef411280df53cdc88daf3119a42649a
  Building wheel for scipy (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\mirij\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\mirij\\AppData\\Local\\Temp\\pip-install-2622e9v0\\scipy_acf572e812824756b123d0834a436e25\\setup.py'"'"'; __file__='"'"'C:\\Users\\mirij\\AppData\\Local\\Temp\\pip-install-2622e9v0\\scipy_acf572e812824756b123d0834a436e25\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\mirij\AppData\Local\Temp\pip-wheel-jfkrd1qh'
       cwd: C:\Users\mirij\AppData\Local\Temp\pip-install-2622e9v0\scipy_acf572e812824756b123d0834a436e25\
  Complete output (122 lines):
  Running from scipy source directory.
  lapack_opt_info:
  lapack_mkl_info:
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries mkl_rt not found in ['C:\\Users\\mirij\\anaconda3\\lib', 'C:\\', 'C:\\Users\\mirij\\anaconda3\\libs']
    NOT AVAILABLE

  openblas_lapack_info:
    libraries openblas not found in ['C:\\Users\\mirij\\anaconda3\\lib', 'C:\\', 'C:\\Users\\mirij\\anaconda3\\libs']
  get_default_fcompiler: matching types: '['gnu', 'intelv', 'absoft', 'compaqv', 'intelev', 'gnu95', 'g95', 'intelvem', 'intelem', 'flang']'
  customize GnuFCompiler
  Could not locate executable g77
  Could not locate executable f77
  customize IntelVisualFCompiler
  Could not locate executable ifort
  Could not locate executable ifl
  customize AbsoftFCompiler
  Could not locate executable f90
  customize CompaqVisualFCompiler
  Could not locate executable DF
  customize IntelItaniumVisualFCompiler
  Could not locate executable efl
  customize Gnu95FCompiler
  Could not locate executable gfortran
  Could not locate executable f95
  customize G95FCompiler
  Could not locate executable g95
  customize IntelEM64VisualFCompiler
  customize IntelEM64TFCompiler
  Could not locate executable efort
  Could not locate executable efc
  customize PGroupFlangCompiler
  Could not locate executable flang
  don't know how to compile Fortran code on platform 'nt'
    NOT AVAILABLE

  openblas_clapack_info:
    libraries openblas,lapack not found in ['C:\\Users\\mirij\\anaconda3\\lib', 'C:\\', 'C:\\Users\\mirij\\anaconda3\\libs']
    NOT AVAILABLE

  flame_info:
    libraries flame not found in ['C:\\Users\\mirij\\anaconda3\\lib', 'C:\\', 'C:\\Users\\mirij\\anaconda3\\libs']
    NOT AVAILABLE

  atlas_3_10_threads_info:
  Setting PTATLAS=ATLAS
    libraries lapack_atlas not found in C:\Users\mirij\anaconda3\lib
    libraries tatlas,tatlas not found in C:\Users\mirij\anaconda3\lib
    libraries lapack_atlas not found in C:\
    libraries tatlas,tatlas not found in C:\
    libraries lapack_atlas not found in C:\Users\mirij\anaconda3\libs
    libraries tatlas,tatlas not found in C:\Users\mirij\anaconda3\libs
  <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
    NOT AVAILABLE

  atlas_3_10_info:
    libraries lapack_atlas not found in C:\Users\mirij\anaconda3\lib
    libraries satlas,satlas not found in C:\Users\mirij\anaconda3\lib
    libraries lapack_atlas not found in C:\
    libraries satlas,satlas not found in C:\
    libraries lapack_atlas not found in C:\Users\mirij\anaconda3\libs
    libraries satlas,satlas not found in C:\Users\mirij\anaconda3\libs
  <class 'numpy.distutils.system_info.atlas_3_10_info'>
    NOT AVAILABLE

  atlas_threads_info:
  Setting PTATLAS=ATLAS
    libraries lapack_atlas not found in C:\Users\mirij\anaconda3\lib
    libraries ptf77blas,ptcblas,atlas not found in C:\Users\mirij\anaconda3\lib
    libraries lapack_atlas not found in C:\
    libraries ptf77blas,ptcblas,atlas not found in C:\
    libraries lapack_atlas not found in C:\Users\mirij\anaconda3\libs
    libraries ptf77blas,ptcblas,atlas not found in C:\Users\mirij\anaconda3\libs
  <class 'numpy.distutils.system_info.atlas_threads_info'>
    NOT AVAILABLE

  atlas_info:
    libraries lapack_atlas not found in C:\Users\mirij\anaconda3\lib
    libraries f77blas,cblas,atlas not found in C:\Users\mirij\anaconda3\lib
    libraries lapack_atlas not found in C:\
    libraries f77blas,cblas,atlas not found in C:\
    libraries lapack_atlas not found in C:\Users\mirij\anaconda3\libs
    libraries f77blas,cblas,atlas not found in C:\Users\mirij\anaconda3\libs
  <class 'numpy.distutils.system_info.atlas_info'>
    NOT AVAILABLE

  accelerate_info:
    NOT AVAILABLE

  lapack_info:
    libraries lapack not found in ['C:\\Users\\mirij\\anaconda3\\lib', 'C:\\', 'C:\\Users\\mirij\\anaconda3\\libs']
    NOT AVAILABLE

  C:\Users\mirij\anaconda3\lib\site-packages\numpy\distutils\system_info.py:1748: UserWarning:
      Lapack (http://www.netlib.org/lapack/) libraries not found.
      Directories to search for the libraries can be specified in the
      numpy/distutils/site.cfg file (section [lapack]) or by setting
      the LAPACK environment variable.
    return getattr(self, '_calc_info_{}'.format(name))()
  lapack_src_info:
    NOT AVAILABLE

  C:\Users\mirij\anaconda3\lib\site-packages\numpy\distutils\system_info.py:1748: UserWarning:
      Lapack (http://www.netlib.org/lapack/) sources not found.
      Directories to search for the sources can be specified in the
      numpy/distutils/site.cfg file (section [lapack_src]) or by setting
      the LAPACK_SRC environment variable.
    return getattr(self, '_calc_info_{}'.format(name))()
    NOT AVAILABLE

  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\mirij\AppData\Local\Temp\pip-install-2622e9v0\scipy_acf572e812824756b123d0834a436e25\setup.py", line 492, in <module>
      setup_package()
    File "C:\Users\mirij\AppData\Local\Temp\pip-install-2622e9v0\scipy_acf572e812824756b123d0834a436e25\setup.py", line 488, in setup_package
      setup(**metadata)
    File "C:\Users\mirij\anaconda3\lib\site-packages\numpy\distutils\core.py", line 135, in setup
      config = configuration()
    File "C:\Users\mirij\AppData\Local\Temp\pip-install-2622e9v0\scipy_acf572e812824756b123d0834a436e25\setup.py", line 395, in configuration
      raise NotFoundError(msg)
  numpy.distutils.system_info.NotFoundError: No lapack/blas resources found.
  ----------------------------------------
  ERROR: Failed building wheel for scipy
  Running setup.py clean for scipy
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\mirij\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\mirij\\AppData\\Local\\Temp\\pip-install-2622e9v0\\scipy_acf572e812824756b123d0834a436e25\\setup.py'"'"'; __file__='"'"'C:\\Users\\mirij\\AppData\\Local\\Temp\\pip-install-2622e9v0\\scipy_acf572e812824756b123d0834a436e25\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
       cwd: C:\Users\mirij\AppData\Local\Temp\pip-install-2622e9v0\scipy_acf572e812824756b123d0834a436e25
  Complete output (9 lines):

  `setup.py clean` is not supported, use one of the following instead:

    - `git clean -xdf` (cleans all files)
    - `git clean -Xdf` (cleans all versioned files, doesn't touch
                        files that aren't checked into the git repo)

  Add `--force` to your command to use it anyway if you must (unsupported).

  ----------------------------------------
  ERROR: Failed cleaning build dir for scipy
Successfully built talos
Failed to build scipy
Installing collected packages: scipy, sklearn, keras, wrangle, geonamescache, kerasplotlib, chances, astetik, talos
  Attempting uninstall: scipy
    Found existing installation: scipy 1.5.2
    Uninstalling scipy-1.5.2:
      Successfully uninstalled scipy-1.5.2
    Running setup.py install for scipy ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\mirij\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\mirij\\AppData\\Local\\Temp\\pip-install-2622e9v0\\scipy_acf572e812824756b123d0834a436e25\\setup.py'"'"'; __file__='"'"'C:\\Users\\mirij\\AppData\\Local\\Temp\\pip-install-2622e9v0\\scipy_acf572e812824756b123d0834a436e25\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\mirij\AppData\Local\Temp\pip-record-5_ocpq8r\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\mirij\anaconda3\Include\scipy'
         cwd: C:\Users\mirij\AppData\Local\Temp\pip-install-2622e9v0\scipy_acf572e812824756b123d0834a436e25\
    Complete output (131 lines):

    Note: if you need reliable uninstall behavior, then install
    with pip instead of using `setup.py install`:

      - `pip install .`       (from a git repo or downloaded source
                               release)
      - `pip install scipy`   (last SciPy release on PyPI)


    Running from scipy source directory.
    lapack_opt_info:
    lapack_mkl_info:
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries mkl_rt not found in ['C:\\Users\\mirij\\anaconda3\\lib', 'C:\\', 'C:\\Users\\mirij\\anaconda3\\libs']
      NOT AVAILABLE

    openblas_lapack_info:
      libraries openblas not found in ['C:\\Users\\mirij\\anaconda3\\lib', 'C:\\', 'C:\\Users\\mirij\\anaconda3\\libs']
    get_default_fcompiler: matching types: '['gnu', 'intelv', 'absoft', 'compaqv', 'intelev', 'gnu95', 'g95', 'intelvem', 'intelem', 'flang']'
    customize GnuFCompiler
    Could not locate executable g77
    Could not locate executable f77
    customize IntelVisualFCompiler
    Could not locate executable ifort
    Could not locate executable ifl
    customize AbsoftFCompiler
    Could not locate executable f90
    customize CompaqVisualFCompiler
    Could not locate executable DF
    customize IntelItaniumVisualFCompiler
    Could not locate executable efl
    customize Gnu95FCompiler
    Could not locate executable gfortran
    Could not locate executable f95
    customize G95FCompiler
    Could not locate executable g95
    customize IntelEM64VisualFCompiler
    customize IntelEM64TFCompiler
    Could not locate executable efort
    Could not locate executable efc
    customize PGroupFlangCompiler
    Could not locate executable flang
    don't know how to compile Fortran code on platform 'nt'
      NOT AVAILABLE

    openblas_clapack_info:
      libraries openblas,lapack not found in ['C:\\Users\\mirij\\anaconda3\\lib', 'C:\\', 'C:\\Users\\mirij\\anaconda3\\libs']
      NOT AVAILABLE

    flame_info:
      libraries flame not found in ['C:\\Users\\mirij\\anaconda3\\lib', 'C:\\', 'C:\\Users\\mirij\\anaconda3\\libs']
      NOT AVAILABLE

    atlas_3_10_threads_info:
    Setting PTATLAS=ATLAS
      libraries lapack_atlas not found in C:\Users\mirij\anaconda3\lib
      libraries tatlas,tatlas not found in C:\Users\mirij\anaconda3\lib
      libraries lapack_atlas not found in C:\
      libraries tatlas,tatlas not found in C:\
      libraries lapack_atlas not found in C:\Users\mirij\anaconda3\libs
      libraries tatlas,tatlas not found in C:\Users\mirij\anaconda3\libs
    <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
      NOT AVAILABLE

    atlas_3_10_info:
      libraries lapack_atlas not found in C:\Users\mirij\anaconda3\lib
      libraries satlas,satlas not found in C:\Users\mirij\anaconda3\lib
      libraries lapack_atlas not found in C:\
      libraries satlas,satlas not found in C:\
      libraries lapack_atlas not found in C:\Users\mirij\anaconda3\libs
      libraries satlas,satlas not found in C:\Users\mirij\anaconda3\libs
    <class 'numpy.distutils.system_info.atlas_3_10_info'>
      NOT AVAILABLE

    atlas_threads_info:
    Setting PTATLAS=ATLAS
      libraries lapack_atlas not found in C:\Users\mirij\anaconda3\lib
      libraries ptf77blas,ptcblas,atlas not found in C:\Users\mirij\anaconda3\lib
      libraries lapack_atlas not found in C:\
      libraries ptf77blas,ptcblas,atlas not found in C:\
      libraries lapack_atlas not found in C:\Users\mirij\anaconda3\libs
      libraries ptf77blas,ptcblas,atlas not found in C:\Users\mirij\anaconda3\libs
    <class 'numpy.distutils.system_info.atlas_threads_info'>
      NOT AVAILABLE

    atlas_info:
      libraries lapack_atlas not found in C:\Users\mirij\anaconda3\lib
      libraries f77blas,cblas,atlas not found in C:\Users\mirij\anaconda3\lib
      libraries lapack_atlas not found in C:\
      libraries f77blas,cblas,atlas not found in C:\
      libraries lapack_atlas not found in C:\Users\mirij\anaconda3\libs
      libraries f77blas,cblas,atlas not found in C:\Users\mirij\anaconda3\libs
    <class 'numpy.distutils.system_info.atlas_info'>
      NOT AVAILABLE

    accelerate_info:
      NOT AVAILABLE

    lapack_info:
      libraries lapack not found in ['C:\\Users\\mirij\\anaconda3\\lib', 'C:\\', 'C:\\Users\\mirij\\anaconda3\\libs']
      NOT AVAILABLE

    C:\Users\mirij\anaconda3\lib\site-packages\numpy\distutils\system_info.py:1748: UserWarning:
        Lapack (http://www.netlib.org/lapack/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [lapack]) or by setting
        the LAPACK environment variable.
      return getattr(self, '_calc_info_{}'.format(name))()
    lapack_src_info:
      NOT AVAILABLE

    C:\Users\mirij\anaconda3\lib\site-packages\numpy\distutils\system_info.py:1748: UserWarning:
        Lapack (http://www.netlib.org/lapack/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [lapack_src]) or by setting
        the LAPACK_SRC environment variable.
      return getattr(self, '_calc_info_{}'.format(name))()
      NOT AVAILABLE

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\mirij\AppData\Local\Temp\pip-install-2622e9v0\scipy_acf572e812824756b123d0834a436e25\setup.py", line 492, in <module>
        setup_package()
      File "C:\Users\mirij\AppData\Local\Temp\pip-install-2622e9v0\scipy_acf572e812824756b123d0834a436e25\setup.py", line 488, in setup_package
        setup(**metadata)
      File "C:\Users\mirij\anaconda3\lib\site-packages\numpy\distutils\core.py", line 135, in setup
        config = configuration()
      File "C:\Users\mirij\AppData\Local\Temp\pip-install-2622e9v0\scipy_acf572e812824756b123d0834a436e25\setup.py", line 395, in configuration
        raise NotFoundError(msg)
    numpy.distutils.system_info.NotFoundError: No lapack/blas resources found.
    ----------------------------------------
  Rolling back uninstall of scipy
  Moving to c:\users\mirij\anaconda3\lib\site-packages\scipy-1.5.2.dist-info\
   from C:\Users\mirij\anaconda3\Lib\site-packages\~cipy-1.5.2.dist-info
ERROR: Command errored out with exit status 1: 'C:\Users\mirij\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\mirij\\AppData\\Local\\Temp\\pip-install-2622e9v0\\scipy_acf572e812824756b123d0834a436e25\\setup.py'"'"'; __file__='"'"'C:\\Users\\mirij\\AppData\\Local\\Temp\\pip-install-2622e9v0\\scipy_acf572e812824756b123d0834a436e25\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\mirij\AppData\Local\Temp\pip-record-5_ocpq8r\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\mirij\anaconda3\Include\scipy' Check the logs for full command output.
```
I assume this has to do with scipy. I tried installing scipy==1.5.2. However, the installation keeps using a cached scipy-1.2.0.tar.gz, that I cannot find anywhere.
Furthermore I have tried to install lapack from: https://icl.cs.utk.edu/lapack-for-windows/lapack/, but I cannot seem to figure this out either. 
I managed to install talos on my pc, but my laptop keeps giving me these errors.

Please help me out.

**Comment by mikkokotila** [comment]
I'm sorry, but this has nothing to do with Talos. What you must do is find out what are the missing packages, like lapack/blas, and then make sure that you can install those ok.

For Scipy, you can try first installing it using a specific version you like. If you believe that Talos is for some reason causing the older version to be installed, you can always install talos without dependencies using the `--no-dependencies` switch.

Closing here, feel free to open new issue if anything.
