### ISSUE TITLE
ImportError: cannot import name 'get_config'

### ISSUE THREAD

**Issue by zonexo** [autonomio/talos#553]
Hi,

I got this error when i run my code with talos in a new cluster. It worked previously on another cluster with the same code.

Traceback (most recent call last):
  File "main_multi_ip=cst_op=c_end_clc_clcd_cm_aoa_opt_talos.py", line 35, in <module>
    import talos
  File "/home/users/nus/tslcph1/.local/lib/python3.6/site-packages/talos/__init__.py", line 14, in <module>
    from . import utils
  File "/home/users/nus/tslcph1/.local/lib/python3.6/site-packages/talos/utils/__init__.py", line 3, in <module>
    from kerasplotlib import TrainingLog as live
  File "/home/users/nus/tslcph1/.local/lib/python3.6/site-packages/kerasplotlib/__init__.py", line 1, in <module>
    from kerasplotlib.traininglog import TrainingLog
  File "/home/users/nus/tslcph1/.local/lib/python3.6/site-packages/kerasplotlib/traininglog.py", line 8, in <module>
    from keras.callbacks import Callback
  File "/home/users/nus/tslcph1/.local/lib/python3.6/site-packages/keras/__init__.py", line 25, in <module>
    from keras import models
  File "/home/users/nus/tslcph1/.local/lib/python3.6/site-packages/keras/models.py", line 19, in <module>
    from keras import backend
  File "/home/users/nus/tslcph1/.local/lib/python3.6/site-packages/keras/backend.py", line 36, in <module>
    from tensorflow.python.eager.context import get_config
ImportError: cannot import name 'get_config'

The version is talos 1.0, installed using "pip install talos --user"

The installation was successful though.
---

**Comment by EllaKnows** [comment]
Hey,

same problem here. Everything was fine few weeks ago, now this error occurs...

**Comment by MerveNazlim** [comment]
Hello,
Anybody solved this problem?

**Comment by mikkokotila** [comment]
Seems to be an issue upstream in TensorFlow. Have a look [here](https://stackoverflow.com/questions/66964492/importerror-cannot-import-name-get-config-from-tensorflow-python-eager-conte).
