### ISSUE TITLE
pip install talos is failing due to sklearn in requirements.txt instead of scikit-learn

### ISSUE THREAD

**Issue by mathav95raj** [autonomio/talos#594]
#### 1) Confirm the below

- [Yes ] My Python version is 3.5 or higher (3.10.10)
- [Yes ] I have searched through the [Issues](https://github.com/autonomio/talos/issues) for a duplicate

`pip install talos` is failing because it is unable to install the deprecated `sklearn` dependency. In the [pypi page](https://pypi.org/project/sklearn/#descriptionl) of sklearn, there is a notice to start using `scikit-learn` instead of `sklearn` .
Request to change this in the requirements.txt and setup.py

Error message of pip installation in a fresh python environment:
```
# pip install talos
Collecting talos
  Downloading talos-1.3-py3-none-any.whl (56 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.4/56.4 kB 419.9 kB/s eta 0:00:00
Collecting wrangle
  Using cached wrangle-0.7.2-py3-none-any.whl (52 kB)
Collecting pandas
  Using cached pandas-2.0.0-cp310-cp310-win_amd64.whl (11.2 MB)
Collecting tensorflow>=2.0.0
  Downloading tensorflow-2.12.0-cp310-cp310-win_amd64.whl (1.9 kB)
Collecting kerasplotlib
  Using cached kerasplotlib-1.0-py3-none-any.whl (4.3 kB)
Collecting statsmodels>=0.11.0
  Downloading statsmodels-0.13.5-cp310-cp310-win_amd64.whl (9.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.1/9.1 MB 6.6 MB/s eta 0:00:00
Collecting astetik
  Using cached astetik-1.13-py3-none-any.whl (5.4 MB)
Collecting tqdm
  Using cached tqdm-4.65.0-py3-none-any.whl (77 kB)
Collecting numpy
  Using cached numpy-1.24.2-cp310-cp310-win_amd64.whl (14.8 MB)
Collecting requests
  Using cached requests-2.28.2-py3-none-any.whl (62 kB)
Collecting chances
  Using cached chances-0.1.9-py3-none-any.whl
Collecting sklearn
  Using cached sklearn-0.0.post4.tar.gz (3.6 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\mat\AppData\Local\Temp\pip-install-7vqejgi5\sklearn_3b7d803e75cb4c48b49276a2db6591fd\setup.py", line 10, in <module>
          LONG_DESCRIPTION = f.read()
        File "C:\Users\mat\AppData\Local\Programs\softy\python\lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 7: character maps to <undefined>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.```

**Comment by xanonimoxp** [comment]
Hi, I had the same problem, but it could be solved just add:
`pip install sklearn==0.0`
In this case it will add the component  sklearn-0.0.post4.tar.

**Comment by mathav95raj** [comment]
Yes I did solve the issue by going for sklearn but from the pypi link I had posted, it can be seen that the scikit learn commuity is recommending to do a pip install of scikit learn instead of sklearn

**Comment by christophsiegl** [comment]
I experience the same issue. workaround from @xanonimoxp works, but I would appreciate a change in the requirements file from sklearn to scikit-learn ...

**Comment by jessicapatricoski** [comment]
Please also fix this in setup.py, it says sklearn there too and it's causing the same issue!
